#!/bin/bash


sudo mkdir /usr/share/cups/model
sudo mkdir /var/spool/lpd

# Optional
sudo apt-get install ia32-libs util-linux

# Use Debs folder or download from Brother
wget http://www.brother.com/pub/bsc/linux/dl … 1.i386.deb
wget http://www.brother.com/pub/bsc/linux/dl … 1.i386.deb
wget http://www.brother.com/pub/bsc/linux/dl … 3.i386.deb
wget http://www.brother.com/pub/bsc/linux/dl … 4.i386.deb

sudo dpkg --force-all -i dcpj315wlpr-1.1.1-1.i386.deb
sudo dpkg --force-all -i dcpj315wcupswrapper-1.1.1-1.i386.deb
sudo dpkg -i brscan3-0.2.11-4.i386.deb
sudo dpkg -i brscan-skey-0.2.1-3.i386.deb

sudo gedit "/lib/udev/rules.d/40-libsane.rules" file.
##Fügen Sie die folgende Zeile am Ende der Geräteliste hinzu.
# Brother scanners
ATTRS{idVendor}=="04f9", ENV{libsane_matched}="yes"

# Restart PC and Add Network Printer using the Printer Management of Mint (Network Printer -> Choose Printer (Predisplayed) -> Drivers will be automatically applied)
